### ISSUE TITLE
Consider rustfmt?

### ISSUE THREAD

**Issue by waywardmonkeys** [antifuchs/ratelimit_meter#11]
Have you considered using rustfmt?

I have this set up to work on file save in my editor and it is quite nice / convenient.

**Comment by antifuchs** [comment]
Yep, I meant to do that. There's a branch that'll run clippy in CI too, I'll add a rustfmt-everything step in addition to editor config to that effect on my end (:

**Comment by antifuchs** [comment]
CI now fails if rustfmt 0.9.0 (version configured in `.travisci.yml`) detects differences, and my editor now reformats, too. Thanks for asking about this - the code is really a lot more readable!
