### ISSUE TITLE
How to share KeyedRateLimiter across threads?

### ISSUE THREAD

**Issue by niklasf** [antifuchs/ratelimit_meter#32]
`KeyedRateLimiter` uses `evmap` under the hood, which makes me think it's designed for concurrent use.

But it looks like it does [not implement Sync](https://docs.rs/ratelimit_meter/4.1.1/ratelimit_meter/state/keyed/struct.KeyedRateLimiter.html#impl-Sync). Do I need a `Mutex` to share it across threads?

**Comment by niklasf** [comment]
Oh ... it's supposed to be cloned. So this question is basically a duplicate of #23.

**Comment by antifuchs** [comment]
Ah! Yep, that's how you do it - the limiter must be cloned due to the Arc/Mutex structure it contains. I hope to document this better (or provide clearly-findable examples) someday soon! (:
